### PR TITLE
add support for  InvokeInflector

### PR DESCRIPTION
**Pull request by tonivdv**
If you agree to merge this in a zf2 support branch (e.g. 1.2) as questioned in #12 .

### CODE REVIEW

**Comment by mikemix** [comment]
@snapshotpl how do you feel about this?

**Comment by tonivdv** [comment]
@mikemix @snapshotpl gentle reminder :)

**Comment by mikemix** [comment]
I guess simple config line won't do any harm.

**Comment by tonivdv** [comment]
@mikemix Thanks, but could you also create a new 1.2 release with that fix? Because that was my initial request too :)

**Comment by mikemix** [comment]
There's a single master branch only without split ZF2 / ZF3 support.

**Comment by tonivdv** [comment]
@mikemix not sure I'm following ... you're saying master is compatible with zf2?

**Comment by mikemix** [comment]
Yes.

**Comment by tonivdv** [comment]
@mikemix Alright. I did not know that. I can't use the latest version due to our limitation to mvc: ^2.7 :-/ ... But this tells me I could "try" to update that on our side.

Many thanks

**Comment by snapshotpl** [comment]
I'm ok with this PR :+1: 

@mikemix @tonivdv master is NOT compatible with zf2 https://github.com/mikemix/TacticianModule/blob/master/composer.json#L7

**Pull request merged**
